---
format: gfm
bibliography: information_structure.bib
execute: 
  echo: false
  message: false
  warning: false
  fig-dpi: 300
  fig-asp: 0.56
  out-width: "100%"
---

```{r}
#| label: setup
#| include: false
library("here")
library("rscopus")
library("tidyr")
library("dplyr")
library("readr")
library("glue")
library("stringr")
library("ggplot2")
library("forcats")
```


```{r}
#| label: scopus-query
#| eval: false
#
# Getting publication data via scopus
#
# set year thresholds
min_year <- 1960
max_year <- 2025

# prep empty output    
out_df <- NULL

# search by year (broken down by year because of 5k limit on records)
for(i in min_year:max_year){
  
  res <- scopus_search(
    query = paste(
      "TITLE-ABS-KEY({information structure} OR {information packaging} OR 
        topic OR focus OR {information focus} OR {contrastive focus} OR
        {new information} OR {old information} OR given OR givenness OR 
        {discourse anaphor} OR contrastiveness OR presupposition OR 
        theme OR rheme OR {presentational focus}) AND 
       EXACTSRCTITLE({Discourse Processes} OR {Journal of Pragmatics} OR 
         {Psychological Science} OR {Journal of Phonetics} OR 
         {Journal of Experimental Linguistics} OR 
         {Applied Psycholinguistics} OR {Second Language Research} OR 
         {Studies in Second Language Acquisition} OR 
         {Bilingualism: Language and Cognition} OR 
         {The Quarterly Journal of Experimental Psychology} OR 
         {Cognition} OR {Journal of Memory and Language} OR 
         {Journal of Experimental Psychology} OR 
         {Learning, Memory, and Cognition} OR 
         {Language, Cognition, and Neuroscience} OR 
         {Behavioral and Brain Science} OR {Glossa} OR 
         {Glossa Psycholinguistics} OR {Linguistic Approaches to Bilingualism} OR 
         {Journal of Linguistics} OR {Natural Language and Linguistic Theory} OR 
         {Linguistic Inquiry} OR {Probus} OR 
         {Language, Cognition and Neuroscience} OR 
         {Annual Review of Linguistics} OR {Frontiers in Language Science} OR 
         {Frontiers in Psychology} OR {Languages} OR {Language} OR 
         {Borealis} OR {Studia Linguistica} OR {Acta Linguistica Hungarica} OR 
         {Linguistics} OR {Frontiers in Psychology}) AND
       PUBYEAR = ", i, "AND 
       SRCTYPE(j)"
    ),
    count = 25,
    max_count = 5000
  )

  n_records <- res$total_results
  
  if (n_records > 5000) {
    stop("Joseph, add a while() loop")
  }

  out_df <- bind_rows(out_df, gen_entries_to_df(res$entries)$df)
  
}

out_df |> 
  write_csv(here("data", "raw", glue("{Sys.Date()}_scopus_out.csv")))

```


```{r}
#| label: tidy-data
#| eval: false

src_is <- read_csv(here("data", "raw", "2025-03-06_scopus_out.csv")) |>
  select(
    title =  'dc:title',
    author = 'dc:creator',
    journal = 'prism:publicationName',
    issn = 'prism:issn',
    volume = 'prism:volume',
    pages = 'prism:pageRange',
    date = 'prism:coverDate',
    display_date = 'prism:coverDisplayDate',
    doi = 'prism:doi',
    citations = 'citedby-count',
  ) |>
  mutate(
    year = lubridate::year(date), 
    journal = str_replace(journal, "&amp;", "&")
  ) |> 
  filter(!is.na(journal)) |> 
  write_csv(here("data", "tidy", "scopus_out_tidy.csv"))
```

```{r}
#| label: play

journal_list <- list(
  j1 = list(
    journal = "Discourse Processes", 
    label = "Discourse Processes", 
    type = "experimental"
  ), 
  j2 = list(
    journal = "Journal of Pragmatics", 
    label = "Journal of Pragmatics", 
    type = "experimental"
  ), 
  j3 = list(
    journal = "Psychological Science", 
    label = "Psychological Science", 
    type = "experimental"
  ), 
  j4 = list(
    journal = "Journal of Phonetics", 
    label = "Journal of Phonetics",
    type = "experimental"
  ), 
  j5 = list(
    journal = "Journal of Experimental Linguistics", 
    label = "Journal of Experimental\nLinguistics", 
    type = "experimental"
  ), 
  j6 = list(
    journal = "Applied Psycholinguistics", 
    label = "Applied\nPsycholinguistics",
    type = "experimental"
  ), 
  j7 = list(
    journal = "Second Language Research", 
    label = "Second Language\nResearch",
    type = "experimental"
  ), 
  j8 = list(
    journal = "Studies in Second Language Acquisition", 
    label = "Studies in Second\nLanguage Acquisition",
    type = "experimental"
  ), 
  j9 = list(
    journal = "Bilingualism: Language and Cognition", 
    label = "Bilingualism: Language and Cognition",
    type = "experimental"
  ), 
  j10 = list(
    journal = "The Quarterly Journal of Experimental Psychology", 
    label = "The Quarterly Journal\nof Experimental Psychology",
    type = "experimental"
  ), 
  j11 = list(
    journal = "Cognition", 
    label = "Cognition",
    type = "experimental"
  ), 
  j12 = list(
    journal = "Journal of Memory and Language", 
    label = "Journal of Memory\nand Language",
    type = "experimental"
  ), 
  j13 = list(
    journal = "Journal of Experimental Psychology", 
    label = "Journal of Experimental\nPsychology",
    type = "experimental"
  ), 
  j14 = list(
    journal = "Learning, Memory, and Cognition", 
    label = "Learning, Memory,\nand Cognition",
    type = "experimental"
  ), 
  j15 = list(
    journal = "Language, Cognition, and Neuroscience", 
    label = "Language, Cognition,\nand Neuroscience",
    type = "experimental"
  ), 
  j16 = list(
    journal = "Behavioral and Brain Science", 
    label = "Behavioral and Brain Science",
    type = "experimental"
  ), 
  j17 = list(
    journal = "Glossa", 
    label = "Glossa",
    type = "experimental"
  ), 
  j18 = list(
    journal = "Glossa Psycholinguistics", 
    label = "Glossa Psycholinguistics",
    type = "experimental"
  ), 
  j19 = list(
    journal = "Linguistic Approaches to Bilingualism", 
    label = "Linguistic Approaches\nto Bilingualism",
    type = "experimental"
  ), 
  j20 = list(
    journal = "Journal of Linguistics", 
    label = "Journal of Linguistics",
    type = "theoretical"
  ), 
  j21 = list(
    journal = "Natural Language and Linguistic Theory", 
    label = "Natural Language and\nLinguistic Theory",
    type = "theoretical"
  ), 
  j22 = list(
    journal = "Linguistic Inquiry", 
    label = "Linguistic Inquiry",
    type = "theoretical"
  ), 
  j23 = list(
    journal = "Probus", 
    label = "Probus",
    type = "theoretical"
  ), 
  j24 = list(
    journal = "Language, Cognition and Neuroscience", 
    label = "Language, Cognition\nand Neuroscience",
    type = "experimental"
  ), 
  j25 = list(
    journal = "Annual Review of Linguistics", 
    label = "Annual Review\nof Linguistics",
    type = "experimental"
  ), 
  j26 = list(
    journal = "Frontiers in Language Science", 
    label = "Frontiers in Language Science",
    type = "experimental"
  ), 
  j27 = list(
    journal = "Frontiers in Psychology", 
    label = "Frontiers in Psychology",
    type = "experimental"
  ), 
  j28 = list(
    journal = "Languages", 
    label = "Languages",
    type = "experimental"
  ), 
  j29 = list(
    journal = "Language", 
    label = "Language",
    type = "theoretical"
  ), 
  j30 = list(
    journal = "Borealis", 
    label = "Borealis",
    type = "theoretical"
  ), 
  j31 = list(
    journal = "Studia Linguistica", 
    label = "Studia Linguistica",
    type = "theoretical"
  ), 
  j32 = list(
    journal = "Acta Linguistica Hungarica", 
    label = "Acta Linguistica Hungarica",
    type = "theoretical"
  ), 
  j33 = list(
    journal = "Linguistics", 
    label = "Linguistics",
    type = "theoretical"
  )
)

journal_filter <- bind_rows(journal_list) |> 
  mutate(journal = str_to_lower(journal)) |> 
  write_csv(here("data", "tidy", "journal_list.csv"))

remove_j <- c("frontiers in psychology", "journal of experimental psychology")

terms <- c(
  "information structure", "information packaging", "topic", "focus", 
  "information focus", "contrastive focus", "new information", 
  "old information", "given", "givenness", "discourse anaphor", 
  "contrastiveness", "presupposition", "theme", "rheme", 
  "presentational focus"
)

dat <- read_csv(here("data", "tidy", "scopus_out_tidy.csv")) |> 
  mutate(
    journal = str_to_lower(journal), 
    contains_kw = str_detect(title, paste(terms, collapse = "|"))
  ) |> 
  filter(
    #journal %in% journal_filter$journal, 
    #!(journal %in% remove_j), 
    contains_kw == TRUE
  ) |> 
  left_join(journal_filter, by = "journal")

n_hits <- nrow(dat)

hits_df <- function(x = 1960, y = 500, lab) {
  out <- tibble(
    x = x, 
    y = y, 
    lab = glue("Approx. {prettyNum(n_hits, big.mark = ',')} entries\n as of 03/01/2025")
  )
  
  return(out)
}
```


```{r}
#| label: fig-line-graph
#| fig-asp: 0.4
n_dat <- dat |> 
  group_by(year) |> 
  count() |> 
  ungroup() |> 
  complete(year = 1960:2025, fill = list(n = 0)) |> 
  mutate(cum_n = cumsum(n)) 

pn_1 <- n_dat |> 
  ggplot() + 
  aes(x = year, y = n) + 
  geom_path(color = "#cc0033", linewidth = 0.7) +
  geom_point(size = 1.5, pch = 21, fill = "#cc0033", color = "white") + 
  #scale_x_continuous(breaks = seq(1960, 2025, 5)) + 
  scale_y_continuous(breaks = seq(0, 135, 15)) + 
  coord_cartesian(ylim = c(0, 135)) + 
  labs(x = NULL, y = "N") + 
  ds4ling::ds4ling_bw_theme(base_size = 10) + 
  theme(axis.title.y.left = element_text(hjust = 1))

pn_2 <- n_dat |> 
  filter(year %in% seq(1960, 2025, 5)) |> 
  ggplot() + 
  aes(x = year, y = cum_n) + 
  geom_path(color = "#cc0033", linewidth = 0.7) +
  geom_point(size = 2, pch = 21, fill = "#cc0033", color = "white") + 
  geom_text(
    data = hits_df(x = 1990, y = 1500), 
    aes(x = x, y = y, label = lab), 
    hjust = 0, size = 2
  ) + 
  #scale_x_continuous(breaks = seq(1960, 2025, 5)) + 
  scale_y_continuous(
    name = "N (cumulative)", position = "right", 
    breaks = seq(0, 2000, 250)
  ) + 
  coord_cartesian(ylim = c(0, 2000)) + 
  labs(x = NULL, y = "N") + 
  ds4ling::ds4ling_bw_theme(base_size = 10) + 
  theme(axis.title.y.right = element_text(hjust = 0))

pn_1 +  pn_2
```

```{r}
#| label: fig-bar-graph
dat |> 
  ggplot() + 
  aes(x = year) + 
  geom_histogram(color = "white", fill = "#cc0033", binwidth = 5) + 
  geom_text(
    data = hits_df(x = 1965, y = 350), 
    aes(x = x, y = y, label = lab), 
    hjust = 0
  ) + 
  scale_x_continuous(breaks = seq(1960, 2025, 5)) + 
  labs(y = "Count", x = NULL) +
  ds4ling::ds4ling_bw_theme(base_size = 13)
```

```{r}
#| label: fig-journals
#| fig-asp: 1
dat |> 
  group_by(label) |> 
  count() |> 
  ungroup() |> 
  na.omit() |> 
  mutate(
    n_total = sum(n), 
    prop = n / n_total, 
    label = fct_reorder(label, .x = n)
  ) |> 
  ggplot() + 
  aes(y = label, x = prop) + 
  geom_segment(aes(x = 0, xend = prop), linewidth = 2) + 
  geom_point(size = 4, pch = 21, fill = "#cc0033", color = "white") + 
  geom_text(
    data = hits_df(x = 0.3, y = 1.75), 
    aes(x = x, y = y, label = lab), 
    hjust = 1
  ) + 
  labs(x = "Proportion", y = NULL) + 
  ds4ling::ds4ling_bw_theme(base_size = 13) + 
  theme(axis.text.y = element_text(size = 7))
```

# References

